version: '3.8'
services:  
    model:
        restart: always
        image: car_price:latest
        container_name: model
        env_file:
            - .env
        expose:
            - "3000:3000" 
        networks:
            - main